### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by Roaders** [cohere-io/google-api-client#1]
Not really an issue but I didn't know where else to discuss this...

So this works with the google client side only path that does not require a client secret AND you managed to refresh tokens?
How did you find the docs for that or is this an unsupported method that might stop working at some point?
I thought the google docs and support for this stuff was pretty poor.

Thanks for pointing me in this direction, when I next have time I'll have a look and see if I can replicate what you've done.

**Comment by kfreytag** [comment]
@Roaders -- I *just* saw your note. Don't know why GitHub never notified me of your "Issue". If you have an accessToken that hasn't expired (they only last 3600 seconds), you can use the API without a clientId or clientSecret.

If, however, you need to refresh the token after that 3600 seconds, you're gonna need to submit your clientId and clientSecret.

You're right that the Google documentation (and documentation on the Interwebs) is pretty crappy. Took quite some experimentation to get this all working.
